epochs: 10
lr: 0.01
momentum: 0.9
batch_size: 1
seed: 33
width: 800
threshold: 0.1
current_dataset: kios
model_output: C:\Users\ajf97\root\software\repositories\calcification_dl\src\models\kios.weights
