epochs: 10
lr: 0.01
momentum: 0.9
batch_size: 1
seed: 33
width: 1000
threshold: 0.97
current_dataset: cbis
model_output: C:\Users\ajf97\root\software\repositories\calcification_dl\src\models\cbis.weights
