defaults:
  - dataset/kios
  - train/train_cbis
  - train/train_kios
  - _self_

src_path: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\src"
favicon: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\app\\assets\\favicon.png"

model_dir: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\src\\models"
pretrained_weights: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\src\\models\\pretrained.weights"

kios_model: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\src\\models\\1.weights"
cbis_model: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\src\\models\\2.weights"

sheba_mean: 0.1572722182674478
sheba_std: 0.16270082671743363
