name: cbis_ddsm
path: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\datasets\\CBIS-DDSM"
images_path: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\datasets\\CBIS-DDSM\\IMAGES"
masks_path: "C:\\Users\\ajf97\\root\\software\\repositories\\calcification_dl\\datasets\\CBIS-DDSM\\MASKS"
